services:
  bot:
    image: joshbuker/discord-bot:latest
    build: .
    depends_on:
      - llm
    env_file:
      - .env
    network_mode: service:llm
    tty: true

  llm:
    image: ollama/ollama
    volumes:
      - ollama:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidiia
              count: 1
              capabilities: [gpu]

volumes:
  ollama: {}
