version: '3'

services:
  bot:
    image: ghcr.io/joshbuker/discord-bot:main
    depends_on:
      - llm
    network_mode: service:llm
    restart: unless-stopped
    tty: true
    environment:
      - RUBY_DISCORD_BOT_TOKEN=${RUBY_DISCORD_BOT_TOKEN:?Please configure RUBY_DISCORD_BOT_TOKEN}
      - OLLAMA_SERVICE_NAME=${OLLAMA_SERVICE_NAME:?Please configure OLLAMA_SERVICE_NAME}
      - DEFAULT_LLM_MODEL=${DEFAULT_LLM_MODEL:-"llama3"}

  llm:
    image: ollama/ollama
    volumes:
      - ollama:/root/.ollama
    #ports:
    #  - "11434:11434"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

volumes:
  ollama: {}
