version: '3'

services:
  bot:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    env_file:
      - ../.env
    volumes:
      - ${PWD}:/workspaces/discord-bot:cached
    command: sleep infinity

  ollama:
    image: ollama/ollama
    # Ollama models
    volumes:
      - ollama:/root/.ollama
    ports:
      - 11434:11434
    # Allow access to nvidia gpu
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  melotts:
    image: timhagel/melotts-api-server
    ports:
      - 8080:8080
    environment:
      DEFAULT_SPEED: 1
      DEFAULT_LANGUAGE: EN
      DEFAULT_SPEAKER_ID: EN-Default

  automatic1111:
    image: ghcr.io/joshbuker/automatic1111-docker:main
    volumes:
      - "~/Stable Diffusion/model:/model:ro"
      - venv:/app/venv
      - repos:/app/repositories
    tty: true
    ports:
      - 7860:7860
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

volumes:
  ollama: {}
  venv: {}
  repos: {}
