version: '3'

services:
  bot:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    env_file:
      - ../.env
    volumes:
      - ${PWD}:/workspaces/discord-bot:cached
    command: sleep infinity
    # network_mode: service:llm

  ollama:
    image: ollama/ollama
    # Ollama models
    volumes:
      - ollama:/root/.ollama
    ports:
      - 11434:11434
    # Allow access to nvidia gpu
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  automatic1111:
    image: ghcr.io/joshbuker/automatic1111-docker:main
    volumes:
      - ~/Models:/model:ro
    tty: true
    ports:
      - 7860:7860
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

volumes:
  ollama: {}
