version: '3'

services:
  bot:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    env_file:
      - ../.env
    volumes:
      - ${PWD}:/workspaces/discord-bot:cached
    command: sleep infinity
    network_mode: service:llm

  llm:
    image: ollama/ollama
    # Ollama models
    volumes:
      - ollama:/root/.ollama
    # Allow access to nvidia gpu
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]

volumes:
  ollama: {}
